// api/src/state/events.js

export const EVENTS = {
  SMS_OPEN: "SMS_OPEN",
  SMS_CLOSE: "SMS_CLOSE",

  BUTTON_PRESSED: "BUTTON_PRESSED",

  TIMER_EXPIRED: "TIMER_EXPIRED",

  CAMERA_CONFIRMED_OPEN: "CAMERA_CONFIRMED_OPEN",
  CAMERA_CONFIRMED_CLOSED: "CAMERA_CONFIRMED_CLOSED",

  SHARE_EXPIRED: "SHARE_EXPIRED",

  PI_OFFLINE: "PI_OFFLINE",
  PI_ONLINE: "PI_ONLINE",

  HEALTH_RECOVERED: "HEALTH_RECOVERED"
};
